# Generated by Django 5.2 on 2026-04-24 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True, verbose_name='日文名称')),
                ('flavor_text_zh', models.TextField(blank=True, null=True, verbose_name='中文描述')),
                ('flavor_text_en', models.TextField(blank=True, null=True, verbose_name='英文描述')),
                ('flavor_text_jp', models.TextField(blank=True, null=True, verbose_name='日文描述')),
                ('effect_zh', models.TextField(blank=True, null=True, verbose_name='中文效果')),
                ('effect_en', models.TextField(blank=True, null=True, verbose_name='英文效果')),
                ('effect_jp', models.TextField(blank=True, null=True, verbose_name='日文效果')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
            ],
            options={
                'verbose_name': '特性',
                'verbose_name_plural': '特性',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('name_jp', models.CharField(max_length=100, verbose_name='日文名称')),
            ],
            options={
                'verbose_name': '颜色',
                'verbose_name_plural': '颜色',
            },
        ),
        migrations.CreateModel(
            name='Genera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('name_jp', models.CharField(max_length=100, verbose_name='日文名称')),
            ],
            options={
                'verbose_name': '属类',
                'verbose_name_plural': '属类',
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('name_jp', models.CharField(max_length=100, verbose_name='日文名称')),
            ],
            options={
                'verbose_name': '栖息地',
                'verbose_name_plural': '栖息地',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True, verbose_name='日文名称')),
                ('flavor_text_zh', models.TextField(blank=True, null=True, verbose_name='中文描述')),
                ('flavor_text_en', models.TextField(blank=True, null=True, verbose_name='英文描述')),
                ('flavor_text_jp', models.TextField(blank=True, null=True, verbose_name='日文描述')),
                ('cost', models.IntegerField(default=0, verbose_name='价格')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类')),
                ('sprite', models.ImageField(blank=True, null=True, upload_to='pocket/items/', verbose_name='道具图片')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
            ],
            options={
                'verbose_name': '道具',
                'verbose_name_plural': '道具',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='唯一标识')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True, verbose_name='日文名称')),
                ('flavor_text_zh', models.TextField(blank=True, null=True, verbose_name='中文描述')),
                ('flavor_text_en', models.TextField(blank=True, null=True, verbose_name='英文描述')),
                ('flavor_text_jp', models.TextField(blank=True, null=True, verbose_name='日文描述')),
                ('type_name', models.CharField(max_length=50, verbose_name='属性')),
                ('power', models.CharField(blank=True, max_length=20, null=True, verbose_name='威力')),
                ('pp', models.IntegerField(blank=True, null=True, verbose_name='PP值')),
                ('accuracy', models.CharField(blank=True, max_length=20, null=True, verbose_name='命中率')),
                ('damage_class', models.CharField(max_length=50, verbose_name='伤害分类')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('name_jp', models.CharField(max_length=100, verbose_name='日文名称')),
            ],
            options={
                'verbose_name': '体型',
                'verbose_name_plural': '体型',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('name_jp', models.CharField(max_length=100, verbose_name='日文名称')),
            ],
            options={
                'verbose_name': '属性',
                'verbose_name_plural': '属性',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('coins', models.IntegerField(default=1000, verbose_name='金币')),
                ('pokeballs', models.IntegerField(default=50, verbose_name='精灵球数量')),
                ('berries', models.IntegerField(default=10, verbose_name='树果数量')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '玩家信息',
                'verbose_name_plural': '玩家信息',
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, unique=True, verbose_name='图鉴编号')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('name_zh', models.CharField(blank=True, max_length=100, null=True, verbose_name='中文名称')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='英文名称')),
                ('name_jp', models.CharField(blank=True, max_length=100, null=True, verbose_name='日文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='简要描述')),
                ('profile', models.TextField(blank=True, null=True, verbose_name='详细简介')),
                ('prototype', models.TextField(blank=True, null=True, verbose_name='设计原型')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='细节相关')),
                ('flavor_text_zh', models.TextField(blank=True, null=True, verbose_name='中文风味文本')),
                ('flavor_text_en', models.TextField(blank=True, null=True, verbose_name='英文风味文本')),
                ('flavor_text_jp', models.TextField(blank=True, null=True, verbose_name='日文风味文本')),
                ('gender_ratio', models.IntegerField(blank=True, null=True, verbose_name='性别比例')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='身高')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='体重')),
                ('genera', models.JSONField(default=list, verbose_name='属类')),
                ('base_happiness', models.IntegerField(default=0, verbose_name='基础亲密度')),
                ('is_legendary', models.BooleanField(default=False, verbose_name='是否传说')),
                ('is_mythical', models.BooleanField(default=False, verbose_name='是否神话')),
                ('stats', models.JSONField(default=list, verbose_name='种族值')),
                ('capture_rate', models.IntegerField(default=0, verbose_name='捕获率')),
                ('base_experience', models.IntegerField(blank=True, null=True, verbose_name='基础经验')),
                ('hatch_counter', models.IntegerField(default=0, verbose_name='孵化步数')),
                ('generation', models.CharField(blank=True, max_length=50, null=True, verbose_name='世代')),
                ('meta', models.JSONField(default=dict, verbose_name='元数据')),
                ('abilities', models.ManyToManyField(related_name='pokemons', to='pocket.ability', verbose_name='特性列表')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket.color', verbose_name='颜色')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket.habitat', verbose_name='栖息地')),
                ('moves', models.ManyToManyField(related_name='pokemons', to='pocket.move', verbose_name='技能列表')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket.shape', verbose_name='体型')),
                ('types', models.ManyToManyField(related_name='pokemons', to='pocket.type', verbose_name='属性列表')),
            ],
            options={
                'verbose_name': '宝可梦',
                'verbose_name_plural': '宝可梦',
            },
        ),
        migrations.CreateModel(
            name='PlayerPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('friendship', models.IntegerField(default=0, verbose_name='亲密度')),
                ('iv', models.IntegerField(default=0, verbose_name='个体值(IV)')),
                ('catch_time', models.DateTimeField(auto_now_add=True, verbose_name='捕获时间')),
                ('is_shiny', models.BooleanField(default=False, verbose_name='是否闪光')),
                ('gender', models.CharField(default='', max_length=10, verbose_name='性别')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemons', to='pocket.player', verbose_name='持有者')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pocket.pokemon', verbose_name='宝可梦')),
            ],
            options={
                'verbose_name': '玩家持有的宝可梦',
                'verbose_name_plural': '玩家持有的宝可梦',
                'db_table': 'pocket_player_pokemon',
                'db_table_comment': '玩家持有的宝可梦',
            },
        ),
        migrations.CreateModel(
            name='Pokedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_seen', models.BooleanField(default=False, verbose_name='是否见过')),
                ('is_caught', models.BooleanField(default=False, verbose_name='是否捕获')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex', to='pocket.player', verbose_name='玩家')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokedex', to='pocket.pokemon', verbose_name='宝可梦')),
            ],
            options={
                'verbose_name': '个人图鉴记录',
                'verbose_name_plural': '个人图鉴记录',
                'unique_together': {('player', 'pokemon')},
            },
        ),
    ]
