# Generated by Django 5.2 on 2026-04-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolution_chains',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='进化链'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='genera',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='属类'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='height',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='体重'),
        ),
    ]
