# Generated by Django 5.2 on 2026-04-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0002_pokemon_evolution_chains_alter_pokemon_genera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='egg_groups',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='蛋组'),
        ),
    ]
