# Generated by Django 5.2 on 2026-04-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0003_pokemon_egg_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片URL'),
        ),
    ]
