# Generated by Django 5.2 on 2026-04-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0004_add_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pocket/pokemon/', verbose_name='图片'),
        ),
    ]
