# Generated by Django 5.2 on 2026-04-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pocket', '0005_alter_pokemon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='effectiveness',
            field=models.JSONField(default=dict, verbose_name='属性克制关系'),
        ),
    ]
