-- 增加 bing必应每日壁纸 分类
delete from wallpaper_classify where id = 30;
insert into wallpaper_classify (id, name, sort, picurl, `select`, enable, created_at, updated_at) values
(30, 'bing必应每日壁纸', 30, 'classify/20250330-尽享美景.jpg', True, False, now(), now());

-- 增加 宝可梦 多个分类
delete from wallpaper_classify where id >= 60;
insert into wallpaper_classify (id, name, sort, picurl, `select`, enable, created_at, updated_at) values
(60, '宝可梦官方壁纸', 60, 'classify/classify_pokemon_official', True, False, now(), now()),
(61, '宝可梦平铺壁纸', 61, 'classify/classify_pokemon_tile.jpg', True, False, now(), now()),
(62, '宝可梦睡眠', 62, 'classify/classify_pokemon_sleep.jpg', True, False, now(), now()),
(63, '宝可梦GO', 63, 'classify/classify_pokemon_go.jpg', True, False, now(), now()),
(64, '宝可梦像素壁纸', 64, 'classify/classify_pokemon_pixel.jpg', True, False, now(), now()),
(79, '宝可梦壁纸', 79, 'classify/classify_pokemon_chaotic.jpg', True, False, now(), now());  -- 混沌的、无序的、杂乱无章的

-- 2025-06-03 10:03:56
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250319-伞状捕猎术.jpg', '20250319 - 伞状捕猎术: 黑鹭捕鱼，乔贝国家公园，博茨瓦纳 (© Paul Souders/Minden PIctures)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250320-春日仙境.jpg', '20250320 - 春日仙境: 美丽盛开的樱花，杭州的春天，中国 (© zhang shuang/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250321-树木万岁.jpg', '20250321 - 树木万岁: 低地雨林上空的薄雾，丹浓谷，沙巴，婆罗洲，马来西亚 (© Nick Garbutt/Alamy)', '必应,每日壁纸,风景,Bing,微软', 3.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250322-水的奇妙世界！.jpg', '20250322 - 水的奇妙世界！: 尼特哈天然井水面上的睡莲，图卢姆，墨西哥 (© Franco Banfi/NPL/Minden)', '必应,每日壁纸,风景,Bing,微软', 3.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250323-雷鸣不可阻挡.jpg', '20250323 - 雷鸣不可阻挡: 鲍曼附近日落时分的闪电和风暴云，布拉斯加州，美国 (© john finney photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250324-高草盛宴.jpg', '20250324 - 高草盛宴: 沙漠象与小象在高高的草丛中觅食，纳米比亚 (© Christophe Courteau/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250325-色彩斑斓的访客.jpg', '20250325 - 色彩斑斓的访客: 向日葵田里的红额金翅雀，德国 (© Juniors Bildarchiv GmbH/Alamy)', '必应,每日壁纸,风景,Bing,微软', 3.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250326-水面下的生命.jpg', '20250326 - 水面下的生命: 水晶河的海牛，佛罗里达州，美国 (© Stephen Frink/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250327-向戏剧致敬.jpg', '20250327 - 向戏剧致敬: 希罗德·阿提库斯剧场，雅典卫城，希腊 (© f11photo/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250328-温暖舒适的摇篮.jpg', '20250328 - 温暖舒适的摇篮: 正在筑巢的雌性黑枕王鹟 (© komkrit tonusin/Alamy)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250329-花海绽放.jpg', '20250329 - 花海绽放: 卡里佐平原国家纪念碑的超级花期，加利福尼亚州，美国 (© Robb Hirsch/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 3.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250330-尽享美景.jpg', '20250330 - 尽享美景: 悉尼港鸟瞰图，新南威尔士州，澳大利亚 (© jamenpercy/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250331-普利亚的“白色之城”.jpg', '20250331 - 普利亚的“白色之城”: 黄昏下的奥斯图尼, 普利亚, 意大利 (© Feng Wei Photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 5.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250401-蹦跳迎接国家青蛙月.jpg', '20250401 - 蹦跳迎接国家青蛙月: 树蛙, 哥斯达黎加 (© Ondrej Prosicky/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.2, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250402-时间的波浪.jpg', '20250402 - 时间的波浪: 凯恩维尔附近荒地的砂岩地层, 犹他州, 美国 (© Chris Moore/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 4.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250403-天空无极限.jpg', '20250403 - 天空无极限: 沃森峰上空的彩虹, 巨人柱国家公园, 亚利桑那州, 美国 (© Frank Staub/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250404-春和景明.jpg', '20250404 - 春和景明: 苏州古镇风景，江苏省，中国 (© gyn9038/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250405-朝圣圣胡安·德·加兹特鲁加特.jpg', '20250405 - 朝圣圣胡安·德·加兹特鲁加特: 日落时分的加兹特鲁加特岛 , 巴斯克地区, 西班牙 (© Eloi_Omella/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250406-伦敦最尖锐的地标.jpg', '20250406 - 伦敦最尖锐的地标: 碎片大厦，伦敦 (© Dennis Fischer Photography/Moment/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250407-你好，海狸！.jpg', '20250407 - 你好，海狸！: 美洲海狸, Moran, 怀俄明州, 美国 (© Enrique Aguirre Aves/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250408-芬芳清新的春天.jpg', '20250408 - 芬芳清新的春天: 春天的水仙花在清晨绽放 (© LedyX/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250409-在繁星闪耀之前.jpg', '20250409 - 在繁星闪耀之前: 纳克索斯岛的蓝色时刻，基克拉泽斯群岛，希腊 (© Sizun Eye/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250410-野性本能.jpg', '20250410 - 野性本能: 靠近巢穴的红狐幼崽 (© WildMedia/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250411-盛放的美好时光.jpg', '20250411 - 盛放的美好时光: 郁金香，荷兰 (© 1111IESPDJ/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250412-改变世界的108分钟.jpg', '20250412 - 改变世界的108分钟: 从国际空间站穹顶俯瞰南太平洋 (© NASA)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250413-让我们一起庆祝宋干节！.jpg', '20250413 - 让我们一起庆祝宋干节！: 班克鲁特的唐赛寺，泰国 (© Ratnakorn Piyasirisorost/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250414-追逐开始！.jpg', '20250414 - 追逐开始！: 圣玛丽亚岛附近的大西洋细吻海豚，亚速尔群岛，葡萄牙 (© Jordi Chias/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250415-梦幻城堡！.jpg', '20250415 - 梦幻城堡！: 卡拉奥拉城堡，格拉纳达，西班牙 (© Ugo Mellone/eStock Photo)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250416-时光通道.jpg', '20250416 - 时光通道: 卡奇纳桥，天然桥国家区，犹他州，美国 (© Alan Majchrowicz/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250417-双重戏剧.jpg', '20250417 - 双重戏剧: 安第斯动冠伞鸟，厄瓜多尔 (© Kit Day/Alamy Stock Photo)', '必应,每日壁纸,风景,Bing,微软', 5.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250418-纪念历史.jpg', '20250418 - 纪念历史: 卡帕多西亚格雷梅国家公园上空的热气球，土耳其 (© Anton Petrus/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250419-国家公园周开始了.jpg', '20250419 - 国家公园周开始了: 锡安国家公园，犹他州，美国 (© Simon Dannhauer/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 5.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250420-复活节兔子要来了.jpg', '20250420 - 复活节兔子要来了: 春天里的野生小兔子 (© Fiona McAllister Photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250421-银河的魔力之下.jpg', '20250421 - 银河的魔力之下: 银河下的约书亚树，加利福尼亚州，美国 (© Chao Zhang/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250422-我们的能源，我们的星球.jpg', '20250422 - 我们的能源，我们的星球: 大棱镜彩泉，黄石国家公园，怀俄明州，美国 (© Ajith Kumar/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250423-波罗的海的魔力.jpg', '20250423 - 波罗的海的魔力: 海利根港斯坦沃德海滩上的沙滩椅，石勒苏益格-荷尔斯泰因州，德国 (© Frank Lukasseck/eStock Photo)', '必应,每日壁纸,风景,Bing,微软', 3.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250424-崎岖山峰与野性水域.jpg', '20250424 - 崎岖山峰与野性水域: 阿拉斯加基奈峡湾国家公园尖顶湾, 阿拉斯加州苏厄德, 美国 (© Wander Photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250425-身着燕尾服的水手们.jpg', '20250425 - 身着燕尾服的水手们: 麦哲伦企鹅, 志愿者角, 福克兰群岛 (© imageBROKER/Matthias Graben/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250426-悬崖、洞穴与清澈的水域.jpg', '20250426 - 悬崖、洞穴与清澈的水域: 印第安头湾, 布鲁斯半岛国家公园, 安大略, 加拿大 (© Maurice Prokaziuk/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250427-就在这里驻足吧.jpg', '20250427 - 就在这里驻足吧: 红木国家公园和州立公园, 加利福尼亚州, 美国 (© Bob Pool/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250428-这只黑斑羚正在何处漫游？.jpg', '20250428 - 这只黑斑羚正在何处漫游？: 莫雷米野生动物保护区的高角羚，博茨瓦纳 (© Paul Souders/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250429-几何之美绽放于此.jpg', '20250429 - 几何之美绽放于此: 维朗德里城堡，卢瓦尔河谷，法国 (© Mint Images/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250430-瀑布声在各国间回响.jpg', '20250430 - 瀑布声在各国间回响: 从巴拉那州看到的伊瓜苏瀑布, 巴西 (© agustavop/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250501-芬芳的传统.jpg', '20250501 - 芬芳的传统: 鸡蛋花，夏威夷，美国 (© Miranda Jans/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250502-绿鹭.jpg', '20250502 - 绿鹭: 维多利亚睡莲上的绿鹭，潘塔纳尔 ，巴西 (© Gerald Corsi/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250503-让我们一起庆祝宇宙.jpg', '20250503 - 让我们一起庆祝宇宙: 拱门国家公园双拱门映衬下的银河，犹他州，美国 (© Adventure_Photo/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250504-欢迎来到纳布星球！.jpg', '20250504 - 欢迎来到纳布星球！: 西班牙广场，塞维利亚，西班牙 (© Horia Merla/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.1, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250505-秀美壮丽的山河.jpg', '20250505 - 秀美壮丽的山河: 日出时分，美丽的喀斯特山脉鸟瞰图，中国桂林 (© zhaojiankang/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250506-不一般的沙漠之旅.jpg', '20250506 - 不一般的沙漠之旅: 一架超轻型飞机飞越纳米比亚沙漠 (© Burt Johnson/Alamy Stock Photo)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250507-岩石上的城堡.jpg', '20250507 - 岩石上的城堡: 邓路斯城堡，安特里姆郡，北爱尔兰 (© DieterMeyrl/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.2, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250508-值得大声欢呼的一天.jpg', '20250508 - 值得大声欢呼的一天: Rhyolite附近山谷中的驴子，内华达州，美国 (© Moelyn Photos/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250509-融入又突出.jpg', '20250509 - 融入又突出: 普通变色龙 (© Photostock-Israel/SPL/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.2, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250510-童话烟囱！.jpg', '20250510 - 童话烟囱！: 巴尔德纳斯雷亚尔斯自然公园的卡斯蒂尔德蒂拉，纳瓦拉，西班牙 (© Eloi_Omella/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250511-以猫科动物的方式庆祝母爱！.jpg', '20250511 - 以猫科动物的方式庆祝母爱！: 豹妈妈正在梳理她的幼崽，Jao保护区，博茨瓦纳 (© Suzi Eszterhas/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250512-紫色的波浪.jpg', '20250512 - 紫色的波浪: 东京的鸢尾花园, 日本 (© M.Arai/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250513-66岁，依然美丽动人.jpg', '20250513 - 66岁，依然美丽动人: 百内国家公园, 巴塔哥尼亚, 智利 (© Marco Bottigelli/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250514-矿石与传奇.jpg', '20250514 - 矿石与传奇: 弗拉维亚港, 苏尔西斯-伊格莱西恩特, 撒丁岛, 意大利 (© Marco Bottigelli/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250515-伦敦时间到！.jpg', '20250515 - 伦敦时间到！: 大本钟和国会大厦, 威斯敏斯特宫, 伦敦, 英国 (© Puthipong Worasaran/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250516-守护濒危生命的一天.jpg', '20250516 - 守护濒危生命的一天: 大绿金刚鹦鹉, 墨西哥 (© Ondrej Prosicky/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.1, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250517-威尼斯式的“甜蜜生活”.jpg', '20250517 - 威尼斯式的“甜蜜生活”: 威尼斯潟湖中的三角洲, 意大利 (© Dimitri Weber/Amazing Aerial Agency)', '必应,每日壁纸,风景,Bing,微软', 4.1, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250518-图卢兹的暮色.jpg', '20250518 - 图卢兹的暮色: 加龙河对面的圣皮埃尔桥，图卢兹，法国 (© Image Professionals GmbH/Alamy)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250519-汉密尔顿山的蜿蜒之路.jpg', '20250519 - 汉密尔顿山的蜿蜒之路: 汉密尔顿山, 旧金山湾区, 加利福尼亚, 美国 (© Jeffrey Lewis/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250520-小翅膀，大作用.jpg', '20250520 - 小翅膀，大作用: 薰衣草上的蜜蜂 (© Anthony Brown/Alamy Stock Photo)', '必应,每日壁纸,风景,Bing,微软', 4.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250521-茶歇时光.jpg', '20250521 - 茶歇时光: 杨家塘村茶园，松阳县，中国 (© feng xu/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250522-猴面包树大道.jpg', '20250522 - 猴面包树大道: 日落时分的猴面包树，猴面包树大道，马达加斯加 (© Framalicious/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250523-为龟喝彩！.jpg', '20250523 - 为龟喝彩！: 停在黄头侧颈龟鼻子上的茱莉亚蝶，亚马逊地区，厄瓜多尔 (© Westend61/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250524-欧洲的野性之美.jpg', '20250524 - 欧洲的野性之美: 挪威尤通黑门山国家公园 (© Marisa Estivill/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250525-绽放于你所在之地.jpg', '20250525 - 绽放于你所在之地: 布伦特伍德湾的布查特花园，不列颠哥伦比亚省，加拿大 (© 2009fotofriends/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 3.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250526-山间奔驰.jpg', '20250526 - 山间奔驰: 沿着岚山保津川行驶的火车，京都，日本 (© Alvin Huang/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.1, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250527-一处海滨奇观.jpg', '20250527 - 一处海滨奇观: 梦娜维尔岩池，悉尼，澳大利亚 (© jamenpercy/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);

-- 2025-07-08 00:26:44.841658
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250528-海獭很重要.jpg', '20250528 - 海獭很重要: 一只海獭漂浮在阿拉斯加海洋国家野生动物保护区的海藻床上，美国 (© Gerry Ellis/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250529-穿越数个世纪的流淌.jpg', '20250529 - 穿越数个世纪的流淌: 米拉韦特，埃布罗河，加泰罗尼亚塔，西班牙 (© Eloi_Omella/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250530-流经烟雾弥漫之地.jpg', '20250530 - 流经烟雾弥漫之地: 小鸽子河，大雾山国家公园，田纳西州, 美国 (© GreenStock/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250531-充满节日氛围节装饰.jpg', '20250531 - 充满节日氛围节装饰: 用彩色丝线串成的香囊，端午节前夕的庙会上，吉林省吉林市，中国 (© Visual China Group/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250601-海底世界.jpg', '20250601 - 海底世界: 格朗特尔岛附近的堡礁，法属新喀里多尼亚 (© Karsten Wrobel/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250602-花的力量.jpg', '20250602 - 花的力量: 一只停在紫锥菊上的灰蝶，洛克菲勒州立公园，纽约 (© Marianne A. Campolongo/Alamy)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250603-为快乐而刹车.jpg', '20250603 - 为快乐而刹车: 乌得勒支桥上的自行车，荷兰 (© George Pachantouris/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250604-卡拉卢纳海滩, 撒丁岛, 意大利.jpg', '20250604 - 卡拉卢纳海滩, 撒丁岛, 意大利: 卡拉卢纳海滩, 撒丁岛, 意大利 (© guenterguni/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250605-隐藏的美景.jpg', '20250605 - 隐藏的美景: 福玛萨瀑布，迪亚曼蒂纳，巴西 (© Pulsar Images/Alamy)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250606-诺曼底登陆日的转折点.jpg', '20250606 - 诺曼底登陆日的转折点: 诺曼底的阿罗芒什莱班 , 法国 (© Horia Merla/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250607-走上高远之路.jpg', '20250607 - 走上高远之路: 松山顶峰, 洛杉矶国家森林公园, 加利福尼亚州, 美国 (© Matthew Kuhns/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250608-来自彼岸的问候.jpg', '20250608 - 来自彼岸的问候: 北海狮, 温哥华岛, 不列颠哥伦比亚省, 加拿大 (© Steve Woods Photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250609-探索君临城.jpg', '20250609 - 探索君临城: 达尔马提亚的杜布罗夫尼克古城，克罗地亚 (© bluejayphoto/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250610-草之河流.jpg', '20250610 - 草之河流: 大沼泽地国家公园的鸟瞰图，佛罗里达州，美国 (© Robert DelVecchio - OcuDrone/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250611-潮汐间的芭蕾.jpg', '20250611 - 潮汐间的芭蕾: 大红鹳，吕德里茨，纳米比亚 (© Karine Aigner/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250612-星空、岩石与孤寂.jpg', '20250612 - 星空、岩石与孤寂: 奇索斯山脉，大弯国家公园，德克萨斯州，美国 (© Dean Fikar/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250613-海洋的隐秘心跳.jpg', '20250613 - 海洋的隐秘心跳: 维拉弗兰卡岛，圣米格尔岛，亚速尔群岛，葡萄牙 (© ARoxo/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250614-静谧之声.jpg', '20250614 - 静谧之声: 五塔峰，多洛米蒂山脉，科尔蒂纳丹佩佐，贝卢诺省，意大利威尼托大区 (© usabin/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250615-羽翼下的父爱.jpg', '20250615 - 羽翼下的父爱: 雄性小美洲鸵与幼鸟，托雷斯德尔潘恩国家公园，巴塔哥尼亚，智利 (© Ignacio Yufera/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 4.2, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250616-远古泳者的现代困境.jpg', '20250616 - 远古泳者的现代困境: 海龟，费尔南多·迪诺罗尼亚群岛，巴西 (© João Vianna/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250617-海岸静谧，野性依旧.jpg', '20250617 - 海岸静谧，野性依旧: 坎伯兰岛国家海岸的海滨森林，乔治亚州，美国 (© Chris Moore/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 4.1, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250618-让授粉游戏开始吧！.jpg', '20250618 - 让授粉游戏开始吧！: 红花石蒜上的柑橘凤蝶 (© lzh/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250619-潮汐与时间交汇之地.jpg', '20250619 - 潮汐与时间交汇之地: 圣卡塔琳娜州的海滩, 巴西 (© CaioCarvalhoPhotography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250620-寻找斑点.jpg', '20250620 - 寻找斑点: 一只马赛长颈鹿妈妈正在给小长颈鹿梳理毛发, 塞伦盖蒂,坦桑尼亚 (© Alberto Cassani/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250621-此花端合在瑶池.jpg', '20250621 - 此花端合在瑶池: 雾中莲花，中国佛山 (© huoguangliang/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250622-一路丛林.jpg', '20250622 - 一路丛林: 亚马逊雨林，厄瓜多尔 (© Mark Fox/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250623-从废墟中重生.jpg', '20250623 - 从废墟中重生: 德累斯顿易北河谷, 德国 (© Sean Pavone/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250624-大自然的耐心之作.jpg', '20250624 - 大自然的耐心之作: 精致拱门, 拱门国家公园, 犹他州, 美国 (© mmac72/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250625-这里举办的是哪个音乐节？.jpg', '20250625 - 这里举办的是哪个音乐节？: 格拉斯顿伯里托尔上的圣迈克尔塔, 格拉斯顿伯里, 萨默塞特郡, 英格兰 (© Gavin Hellier/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250626-海岸线附近的“马戏”.jpg', '20250626 - 海岸线附近的“马戏”: 马头岩上空的银河, 新南威尔士州, 澳大利亚 (© Philip Thurston/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250627-古冰川遗迹之地.jpg', '20250627 - 古冰川遗迹之地: Knuthöjdsmossen自然保护区, 海勒福什市, 瑞典 (© Sven Halling/DEEPOL/plainpicture)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250628-从实用建筑到地标象征.jpg', '20250628 - 从实用建筑到地标象征: 曼海姆水塔, 德国 (© no limit pictures/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250629-哪里让历史变得“辛辣”.jpg', '20250629 - 哪里让历史变得“辛辣”: Pulau Ay蓝色泻湖, 班达群岛, 印度尼西亚 (© fabio lamanna/Alamy Stock Photo)', '必应,每日壁纸,风景,Bing,微软', 4.9, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250630-是谁击中了地面？.jpg', '20250630 - 是谁击中了地面？: 沃尔夫溪陨石坑, 澳大利亚 (© Abstract Aerial Art/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.4, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250701-原始渔村的风貌.jpg', '20250701 - 原始渔村的风貌: Tilting渔村, 福戈岛 , 纽芬兰和拉布拉多省, 加拿大 (© FedevPhoto/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250702-触手之间的依赖.jpg', '20250702 - 触手之间的依赖: 被泡尖海葵包围的刺颊海葵鱼，米尔恩湾，巴布亚新几内亚 (© Fred Bavendam/Nature Picture Library)', '必应,每日壁纸,风景,Bing,微软', 5.0, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250703-彩虹河的清澈拥抱.jpg', '20250703 - 彩虹河的清澈拥抱: 彩虹泉州立公园的彩虹河，佛罗里达州，美国 (© Michel Roggo/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 4.8, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250704-水、空气、岩石.jpg', '20250704 - 水、空气、岩石: 奥罗塞，撒丁岛，意大利 (© EyeEm Mobile GmbH/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250705-优雅而低调的巨人.jpg', '20250705 - 优雅而低调的巨人: Cize-Bolozon viaduct crossing the Ain gorge, France (© Leonid Andronov/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 3.6, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250706-时光沙丘.jpg', '20250706 - 时光沙丘: 死亡谷国家公园的梅斯基特平原沙丘，加利福尼亚州，美国 (© Bryan Jolley/TANDEM Stills + Motion)', '必应,每日壁纸,风景,Bing,微软', 4.5, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250707-闪电俯冲、水花四溅，然后开吃.jpg', '20250707 - 闪电俯冲、水花四溅，然后开吃: 潜水捕鱼的北方鲣鸟，设得兰群岛，苏格兰 (© Richard Shucksmith/Minden Pictures)', '必应,每日壁纸,风景,Bing,微软', 4.3, 'Bing', TRUE, FALSE, NOW(), NOW(), 30);

-- 2025-07-08 10:57:35.842696
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/0e3b294beb09239a0625d82a2e2c0561.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 5.0, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/1e33nsglt3sztkdty3wrty7lk.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.4, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/1ilo1s6e5xrfj91gkceayjc3q.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.6, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/1joasef2195jccp6aqyb1blrp.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.9, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/1qw1tvj8juego4zd4rqrzpn3x.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.1, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/2equy99fkf7c1cg8xoky7k6x8.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.2, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/2ou8v0pz119oxqy11v4406b5u.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.3, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/2vnwx5lx730ydrlccyfxu3vng.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.6, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/3u483rw8xx24jteuch0r35vym.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.9, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/41ufmfk5tie58brkfmlfl49ai.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.1, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/48q5xj3zatdsag611t5wa7zx0.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.3, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/49z8j8fbcizf2wy1f60xynf3q.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.4, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/4bdwgg3u82drl3gt5eh68e28l.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.6, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/4rqsghcjtgdqu700lyo8qgvz5.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.4, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/510j8lamcv9hiyir0jo83l71b.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.8, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/57x134n9nz27sqp8q6lwzy7y6.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.3, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/59cv2davcazikl05x06lo1s3o.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.9, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/5cv4dok752i6v5b9bnpsx5e3a.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.7, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/5ya4nxgkgraxz0dzlle6ov1n.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.7, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/65nvjotj2dn35y0qio95xib1e.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.5, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/6m7zvehq8wwqsdzrkn0kh9cy3.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.2, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/7ko6k1bnknv26ej5n8cv1qoop.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.5, '', TRUE, FALSE, NOW(), NOW(), 62);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_pokemon_sleep/ftylzmtyk0yf11zbmmsjnw92.jpg', '和卡比兽一起睡觉吧！', '宝可梦,卡比兽,睡觉,pokemon,kabigon,sleep', 4.4, '', TRUE, FALSE, NOW(), NOW(), 62);

-- 2025-08-01 10:19:18.819277
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250708-锋芒毕露的美.jpg', '和卡比兽一起睡觉吧！', '必应,每日壁纸,风景,Bing,微软', 4.1, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250709-具有纪念意义的火车站.jpg', '和卡比兽一起睡觉吧！', '必应,每日壁纸,风景,Bing,微软', 4.1, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250710-奔向自由之浪.jpg', '20250710 - 奔向自由之浪: 巴哈马的绿松石色水域 (© BlueOrange Studio/Adobe Stock)', '必应,每日壁纸,风景,Bing,微软', 4.8, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250711-把我们都算上.jpg', '20250711 - 把我们都算上: 日出时的东京，日本 (© pongnathee kluaythong/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250712-跟随妈妈的脚步.jpg', '20250712 - 跟随妈妈的脚步: 汤氏瞪羚母亲和小鹿，马赛马拉，肯尼亚 (© Gallo Images/DanitaDelimont.com)', '必应,每日壁纸,风景,Bing,微软', 4.1, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250713-层层叠叠的岩石.jpg', '20250713 - 层层叠叠的岩石: 卡尔夫沙马尔斯维克湾玄武岩柱，斯卡吉半岛，冰岛 (© Arterra Picture Library/Alamy Stock Photo)', '必应,每日壁纸,风景,Bing,微软', 4.1, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250714-追逐海浪，掀起潮汐.jpg', '20250714 - 追逐海浪，掀起潮汐: 加利西亚海域游弋的幼年大青鲨，西班牙 (© Damocean/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250715-永恒的光芒.jpg', '20250715 - 永恒的光芒: 英仙座流星雨和一棵古老刺果松，大盆地国家公园，内华达州，美国 (© Wirestock Creators/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.3, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250716-伊西斯女神的光辉照耀下.jpg', '20250716 - 伊西斯女神的光辉照耀下: 菲莱神庙 (aka Temple of Isis), 阿斯旺, 埃及 (© Ratnakorn Piyasirisorost/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250717-追随香气的地平线.jpg', '20250717 - 追随香气的地平线: 瓦朗索勒高原的薰衣草田，法国 (© zpagistock/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250718-一切准备就绪，等待日落.jpg', '20250718 - 一切准备就绪，等待日落: 塞里雅兰瀑布日落美景，冰岛 (© Tom Mackie/AWL/plainpicture)', '必应,每日壁纸,风景,Bing,微软', 4.0, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250719-化石、瀑布与林间小径.jpg', '20250719 - 化石、瀑布与林间小径: 幽鹤国家公园的伯吉斯山和翡翠湖, 不列颠哥伦比亚省, 加拿大 (© Feng Wei Photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250720-在月光下起舞.jpg', '20250720 - 在月光下起舞: 望远镜下的月球表面照片 (© Sergey Kuznetsov/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250721-海洋中的热带雨林.jpg', '20250721 - 海洋中的热带雨林: 浅海中的鹿角珊瑚 (© blue-sea.cz/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.7, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250722-天山上的蓝宝石.jpg', '20250722 - 天山上的蓝宝石: 夏季的赛里木湖，博尔塔拉蒙古自治州博乐县, 中国新疆维吾尔自治区 (© Feng Wei Photography/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.3, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250723-城中之国.jpg', '20250723 - 城中之国: 梵蒂冈城与圣彼得大教堂，罗马，意大利 (© RudyBalasko/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.8, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250724-物以类聚，鸟以群分.jpg', '20250724 - 物以类聚，鸟以群分: 栖息在树枝上的灰燕鵙家族 (© Captain Skyhigh/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250725-生活的画卷.jpg', '20250725 - 生活的画卷: 大加那利岛拉斯帕尔马斯色彩缤纷的房屋鸟瞰图，西班牙 (© Marco Bottigelli/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.7, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250726-潮汐的守护者.jpg', '20250726 - 潮汐的守护者: 黄昏时的红树林，瓦拉基里海滩，松巴岛，印度尼西亚 (© Boonchet Ch./Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.5, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250727-同步闪耀.jpg', '20250727 - 同步闪耀: 黑鳍梭鱼群，鲨鱼礁，拉斯穆罕默德国家公园，西奈半岛，埃及 (© Alex Mustard/Nature Picture Library)', '必应,每日壁纸,风景,Bing,微软', 4.6, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250728-领先一步.jpg', '20250728 - 领先一步: 蒙古草原上的蒙古包 (© Michel Arnault/Shutterstock)', '必应,每日壁纸,风景,Bing,微软', 4.9, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250729-丛林女王.jpg', '20250729 - 丛林女王: 雌性孟加拉虎，坎哈国家公园，印度 (© Axel Gomille/Nature Picture Library)', '必应,每日壁纸,风景,Bing,微软', 4.9, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250730-理想的世界！.jpg', '20250730 - 理想的世界！: 里瓦德塞利亚，阿斯图里亚斯，西班牙 (© Agnieszka Glowala/Getty Images)', '必应,每日壁纸,风景,Bing,微软', 4.6, '', TRUE, FALSE, NOW(), NOW(), 30);
INSERT INTO wallpaper_wall (picurl, description, tabs, score, publisher, is_active, is_locked, created_at, updated_at, classify_id) VALUES ('pics/classify_bing/20250731-远离尘嚣.jpg', '20250731 - 远离尘嚣: 纳帕利海岸的卡拉劳海滩, 可爱岛, 夏威夷, 美国 (© Russ Bishop/DanitaDelimont.com)', '必应,每日壁纸,风景,Bing,微软', 5.0, '', TRUE, FALSE, NOW(), NOW(), 30);

