# Generated by Django 5.1.6 on 2025-03-28 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='ip地址')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('access_time', models.DateTimeField(verbose_name='访问时间')),
            ],
            options={
                'verbose_name': '请求访问信息',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, verbose_name='跳转链接地址')),
                ('sort', models.IntegerField(verbose_name='排序字段')),
                ('picurl', models.CharField(max_length=255, verbose_name='缩略图')),
                ('target', models.CharField(max_length=60, verbose_name='跳转方式，默认：self，外站：miniProgram')),
                ('appid', models.CharField(max_length=100, verbose_name='外部小程序的app-id')),
            ],
            options={
                'verbose_name': '首页横幅',
                'verbose_name_plural': '首页横幅_plural',
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='db_comment中显示的名称: 分类名称', max_length=100, unique=True, verbose_name='分类名称')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('picurl', models.CharField(max_length=255, verbose_name='图片地址')),
                ('select', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '壁纸分类',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告详情')),
                ('author', models.CharField(max_length=60, verbose_name='发布者')),
                ('article_status', models.BooleanField(default=True, verbose_name='公告状态')),
                ('publish_date', models.DateTimeField(verbose_name='发布时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '公告信息',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('address', models.CharField(max_length=60, verbose_name='归属地')),
                ('ip', models.CharField(max_length=100, verbose_name='ip地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picurl', models.CharField(max_length=255, verbose_name='图片地址')),
                ('description', models.CharField(max_length=255, verbose_name='描述')),
                ('tabs', models.CharField(max_length=200, verbose_name='标签')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='图片分数')),
                ('author', models.CharField(default='unknown', max_length=60, verbose_name='作者')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.classify')),
            ],
            options={
                'verbose_name': '壁纸信息',
                'verbose_name_plural': '壁纸详细信息',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='用户id')),
                ('pic_score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='壁纸分数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wall_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.wall', verbose_name='壁纸id')),
            ],
            options={
                'verbose_name': '用户评分',
            },
        ),
    ]
