# Generated by Django 5.1.6 on 2025-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0002_alter_classify_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classify',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
