# Generated by Django 5.1.6 on 2025-04-02 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0003_alter_classify_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': '请求访问信息'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name_plural': '公告信息'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name_plural': '用户评分'},
        ),
        migrations.RenameField(
            model_name='classify',
            old_name='is_active',
            new_name='enable',
        ),
        migrations.AddField(
            model_name='classify',
            name='_id',
            field=models.CharField(max_length=60, null=True, verbose_name='分类id'),
        ),
        migrations.AddField(
            model_name='wall',
            name='_id',
            field=models.CharField(max_length=60, null=True, verbose_name='图片id'),
        ),
        migrations.AlterField(
            model_name='access',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
