# Generated by Django 5.1.6 on 2025-04-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0004_alter_access_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='_classid',
            field=models.CharField(max_length=60, null=True, verbose_name='分类id'),
        ),
    ]
