# Generated by Django 5.1.6 on 2025-04-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0005_wall__classid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.CharField(max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='图片分数'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='tabs',
            field=models.CharField(max_length=200, null=True, verbose_name='标签'),
        ),
    ]
