# Generated by Django 5.1.6 on 2025-04-02 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0006_alter_wall_description_alter_wall_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='author',
        ),
        migrations.AddField(
            model_name='wall',
            name='publisher',
            field=models.CharField(default='unknown', max_length=60, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.classify', verbose_name='分类'),
        ),
    ]
