# Generated by Django 5.1.6 on 2025-04-03 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0007_remove_wall_author_wall_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='banner',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='图片分数'),
        ),
    ]
