# Generated by Django 5.1.6 on 2025-04-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0008_banner_created_at_banner_enable_alter_wall_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appilcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='应用名称')),
                ('enable', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'app应用',
                'verbose_name_plural': 'App应用管理',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='url地址')),
                ('pv', models.IntegerField(default=0, verbose_name='页面访问量')),
            ],
            options={
                'verbose_name': '页面访问量',
                'verbose_name_plural': '页面访问量统计',
            },
        ),
    ]
