# Generated by Django 5.1.6 on 2025-04-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0009_appilcation_pageview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appilcation',
            new_name='Application',
        ),
    ]
