# Generated by Django 5.1.6 on 2025-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0010_rename_appilcation_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='logo',
            field=models.CharField(max_length=255, null=True, verbose_name='logo图片'),
        ),
    ]
