# Generated by Django 5.1.6 on 2025-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0011_application_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='logo',
        ),
        migrations.AddField(
            model_name='application',
            name='logo_url',
            field=models.CharField(max_length=255, null=True, verbose_name='logo图片url'),
        ),
    ]
