# Generated by Django 5.1.6 on 2025-04-10 03:28

import django.db.models.deletion
import django.db.models.functions.datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0012_remove_application_logo_application_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='wall_id',
            new_name='wall',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wall',
            old_name='class_id',
            new_name='classify',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user_id',
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.user', verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
