# Generated by Django 5.1.6 on 2025-04-10 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0014_alter_classify_created_at_alter_classify_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.wall', verbose_name='壁纸id'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallpaper.classify', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='用户名')),
                ('email', models.CharField(max_length=60, verbose_name='邮箱地址')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('source', models.CharField(max_length=60, verbose_name='来源')),
                ('ip', models.CharField(max_length=60, verbose_name='ip地址')),
                ('region', models.CharField(max_length=60, verbose_name='行政区省市县')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户资料',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
