# Generated by Django 5.1.6 on 2025-04-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0015_alter_rate_user_alter_rate_wall_alter_wall_classify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='appid',
            field=models.CharField(max_length=100, null=True, verbose_name='外部小程序的app-id'),
        ),
    ]
