# Generated by Django 5.1.6 on 2025-04-11 02:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0016_alter_banner_appid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='用户名')),
                ('email', models.CharField(max_length=60, null=True, verbose_name='邮箱地址')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='电话')),
                ('source', models.CharField(max_length=60, verbose_name='来源')),
                ('ip', models.CharField(max_length=60, verbose_name='ip地址')),
                ('region', models.CharField(max_length=60, null=True, verbose_name='行政区省市县')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户个人信息',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
