# Generated by Django 5.1.6 on 2025-04-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0017_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='logo_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='logo图片url'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='appid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='外部小程序的app-id'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='分类id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='行政区省市县'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='_classid',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='分类id'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='图片id'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='图片分数'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='tabs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标签'),
        ),
    ]
