# Generated by Django 5.1.6 on 2025-04-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0018_alter_application_logo_url_alter_banner_appid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='select',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
