# Generated by Django 5.2 on 2025-05-28 01:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0019_notice_select'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='db_comment中显示的名称: 分类名称', max_length=100, unique=True, verbose_name='专题名称')),
                ('content', models.TextField(blank=True, null=True, verbose_name='专题内容')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('picurl', models.CharField(max_length=255, verbose_name='图片地址')),
                ('select', models.BooleanField(default=False, verbose_name='是否首页推荐')),
                ('enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '壁纸专题',
            },
        ),
        migrations.RemoveField(
            model_name='classify',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='wall',
            name='_classid',
        ),
        migrations.RemoveField(
            model_name='wall',
            name='_id',
        ),
        migrations.AddField(
            model_name='wall',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='walls', to='wallpaper.subject', verbose_name='专题'),
        ),
    ]
