# Generated by Django 5.2 on 2025-06-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0020_subject_remove_classify__id_remove_wall__classid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '公告', 'verbose_name_plural': '公告信息'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '用户个人信息s'},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'verbose_name': '用户评分', 'verbose_name_plural': '用户评分'},
        ),
        migrations.AlterModelOptions(
            name='wall',
            options={'verbose_name': '壁纸', 'verbose_name_plural': '壁纸信息'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='source',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='来源'),
        ),
    ]
