# Generated by Django 5.2 on 2025-06-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0021_alter_notice_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wechat_openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='微信openid'),
        ),
    ]
