# Generated by Django 5.2 on 2025-06-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0023_rename_mobile_number_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avater',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='头像'),
        ),
    ]
