# Generated by Django 5.2 on 2025-07-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0024_profile_avater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name_plural': '访问日志'},
        ),
        migrations.AddField(
            model_name='access',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='访问地址'),
        ),
        migrations.AlterField(
            model_name='access',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='publisher',
            field=models.CharField(blank=True, default='unknown', max_length=60, null=True, verbose_name='发布者'),
        ),
    ]
