# Generated by Django 5.2 on 2025-07-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0025_alter_access_options_access_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='渠道'),
        ),
        migrations.AddField(
            model_name='access',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='平台'),
        ),
        migrations.AddField(
            model_name='access',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='access',
            name='access_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='access',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='来源'),
        ),
    ]
