# Generated by Django 5.2 on 2025-07-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0026_access_channel_access_platform_access_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
