# Generated by Django 5.2 on 2025-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0027_alter_access_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='remark',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='备注'),
        ),
    ]
