# Generated by Django 5.2 on 2025-07-10 03:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0028_alter_access_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间'),
        ),
    ]
