# Generated by Django 5.2 on 2025-07-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0029_alter_access_access_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='enable',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='classify',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='需要解锁'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='是否需要解锁'),
        ),
        migrations.AddField(
            model_name='wall',
            name='is_lock',
            field=models.BooleanField(default=False, verbose_name='是否需要解锁'),
        ),
        migrations.AlterField(
            model_name='access',
            name='access_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
