# Generated by Django 5.2 on 2025-07-17 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0030_rename_enable_subject_is_active_classify_is_lock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classify',
            old_name='is_lock',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='is_lock',
            new_name='is_locked',
        ),
        migrations.RenameField(
            model_name='wall',
            old_name='is_lock',
            new_name='is_locked',
        ),
    ]
