# Generated by Django 5.2 on 2025-08-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpaper", "0031_rename_is_lock_classify_is_locked_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="access",
            options={"verbose_name": "访问日志详情", "verbose_name_plural": "访问日志"},
        ),
        migrations.AlterField(
            model_name="classify",
            name="name_en",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name="分类英文名称"),
        ),
        migrations.AddField(
            model_name="wall",
            name="downloads",
            field=models.IntegerField(default=0, verbose_name="下载量"),
        ),
        migrations.AddField(
            model_name="wall",
            name="views",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
        migrations.AlterField(
            model_name="access",
            name="remark",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="备注"),
        ),
    ]
