# Generated by Django 5.2 on 2025-08-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallpaper", "0032_alter_access_options_remove_access_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="access",
            name="source",
        )
    ]
