# Generated by Django 5.2 on 2025-10-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0033_remove_access_source_alter_classify_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='downloads',
            field=models.IntegerField(db_default=0, default=0, verbose_name='下载量'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='views',
            field=models.IntegerField(db_default=0, default=0, verbose_name='浏览量'),
        ),
    ]
