# Generated by Django 5.2 on 2025-12-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0034_alter_wall_downloads_alter_wall_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='备注'),
        ),
    ]
