# Generated by Django 5.2 on 2025-12-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0035_wall_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='classify',
            name='pic_path_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片所在路径前缀'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='picurl',
            field=models.CharField(max_length=255, unique=True, verbose_name='图片地址'),
        ),
    ]
