# Generated by Django 5.2 on 2025-12-31 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0036_classify_pic_path_prefix_alter_wall_picurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60, verbose_name='反馈类型')),
                ('content', models.CharField(max_length=255, verbose_name='反馈内容')),
                ('contact', models.IntegerField(default=0, verbose_name='联系方式')),
                ('is_deal', models.BooleanField(default=False, verbose_name='处理状态')),
                ('images', models.JSONField(blank=True, max_length=255, null=True, verbose_name='图片地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '反馈信息',
                'verbose_name_plural': '反馈信息',
            },
        ),
        migrations.AlterField(
            model_name='classify',
            name='pic_path_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='图片所在路径'),
        ),
        migrations.CreateModel(
            name='UserWallMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_collect', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('is_download', models.BooleanField(default=False, verbose_name='是否下载')),
                ('pic_score', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True, verbose_name='壁纸评分')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
                ('wall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.wall', verbose_name='壁纸id')),
            ],
            options={
                'verbose_name': '用户壁纸关系信息',
                'verbose_name_plural': '用户壁纸关系',
            },
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
