# Generated by Django 5.2 on 2025-12-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0037_feedback_alter_classify_pic_path_prefix_userwallmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系方式'),
        ),
    ]
