# Generated by Django 5.2 on 2026-02-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0039_rename_userwallmap_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='profile',
            name='energy',
            field=models.IntegerField(default=0, verbose_name='用户能量值'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否vip'),
        ),
    ]
