# Generated by Django 5.2 on 2026-02-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0040_profile_description_profile_energy_profile_is_vip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actions',
            options={'verbose_name': '用户行为信息', 'verbose_name_plural': '用户行为'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='avater',
            new_name='avatar',
        ),
        migrations.AddField(
            model_name='profile',
            name='channel',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ip',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='ip地址'),
        ),
    ]
