# Generated by Django 5.2 on 2026-03-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0041_alter_actions_options_rename_avater_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': '访问日志详情', 'verbose_name_plural': '访问日志_plural'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页横幅', 'verbose_name_plural': '首页横幅'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '用户个人信息'},
        ),
        migrations.AddField(
            model_name='access',
            name='app_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='app版本号'),
        ),
        migrations.AddField(
            model_name='subject',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='专题英文内容'),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='专题英文名称'),
        ),
        migrations.AddField(
            model_name='subject',
            name='tabs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='wall',
            name='description_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='英文描述'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(db_comment='db_comment中显示的名称: 专题名称', max_length=100, unique=True, verbose_name='专题名称'),
        ),
    ]
