# Generated by Django 5.2 on 2026-03-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0042_alter_access_options_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WallSimilarities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_wall_id', models.IntegerField(verbose_name='源壁纸ID')),
                ('target_wall_id', models.IntegerField(verbose_name='目标壁纸ID')),
                ('similarity', models.FloatField(blank=True, null=True, verbose_name='相似度')),
                ('rank_in_list', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '壁纸相似度',
                'verbose_name_plural': '壁纸相似度',
            },
        ),
        migrations.AddField(
            model_name='wall',
            name='content_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='内容哈希值'),
        ),
        migrations.AddField(
            model_name='wall',
            name='md5_hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MD5哈希值'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sort',
            field=models.IntegerField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='图片分数'),
        ),
        migrations.CreateModel(
            name='WallFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.BinaryField(blank=True, null=True, verbose_name='特征向量')),
                ('model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='模型名称')),
                ('feature_dim', models.IntegerField(blank=True, null=True, verbose_name='特征维度')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wall_features', to='wallpaper.wall')),
            ],
            options={
                'verbose_name': '壁纸特征向量',
                'verbose_name_plural': '壁纸特征向量',
            },
        ),
    ]
