# Generated by Django 5.2 on 2026-03-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0043_wallsimilarities_wall_content_hash_wall_md5_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallfeatures',
            name='id',
        ),
        migrations.AlterField(
            model_name='wallfeatures',
            name='wall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wall_features', serialize=False, to='wallpaper.wall'),
        ),
        migrations.AlterModelTable(
            name='wallfeatures',
            table='wall_features',
        ),
        migrations.AlterModelTable(
            name='wallsimilarities',
            table='wall_similarities',
        ),
    ]
