# Generated by Django 5.2 on 2026-03-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0044_remove_wallfeatures_id_alter_wallfeatures_wall_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wallfeatures',
            table='wallpaper_wall_features',
        ),
        migrations.AlterModelTable(
            name='wallsimilarities',
            table='wallpaper_wall_similarities',
        ),
    ]
