# Generated by Django 5.2 on 2026-03-31 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0045_alter_wallfeatures_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='wall',
            table_comment='壁纸信息，存储壁纸的基本信息',
        ),
        migrations.AlterModelTableComment(
            name='wallfeatures',
            table_comment='壁纸特征向量，存储图片的特征向量用于相似度计算',
        ),
        migrations.AlterModelTableComment(
            name='wallsimilarities',
            table_comment='壁纸相似度，用于存储壁纸之间的相似度关系',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='wallsimilarities',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wall',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='wallsimilarities',
            name='similarity',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='相似度'),
        ),
        migrations.AlterField(
            model_name='wallsimilarities',
            name='source_wall_id',
            field=models.IntegerField(db_index=True, verbose_name='源壁纸ID'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['classify', 'updated_at'], name='wallpaper_w_classif_b6c121_idx'),
        ),
    ]
