# Generated by Django 5.2 on 2026-04-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0046_alter_wall_table_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallsimilarities',
            name='rank_in_list',
        ),
        migrations.AlterField(
            model_name='wallsimilarities',
            name='similarity',
            field=models.FloatField(blank=True, null=True, verbose_name='相似度'),
        ),
        migrations.AlterField(
            model_name='wallsimilarities',
            name='source_wall_id',
            field=models.IntegerField(verbose_name='源壁纸ID'),
        ),
        migrations.AddIndex(
            model_name='wallsimilarities',
            index=models.Index(fields=['source_wall_id', '-similarity'], name='idx_source_wall_id_similarity'),
        ),
        migrations.AddConstraint(
            model_name='wallsimilarities',
            constraint=models.UniqueConstraint(fields=('source_wall_id', 'target_wall_id'), name='unique_source_target'),
        ),
    ]
