# Generated by Django 5.2 on 2026-04-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0047_remove_wallsimilarities_rank_in_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=100, verbose_name='渠道')),
                ('platform', models.CharField(max_length=100, verbose_name='平台')),
                ('app_store_url', models.CharField(max_length=255, verbose_name='应用商店地址')),
                ('app_version', models.CharField(max_length=100, verbose_name='app版本号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '版本信息',
                'verbose_name_plural': '版本信息',
            },
        ),
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_classif_b6c121_idx',
        ),
        migrations.AlterField(
            model_name='access',
            name='access_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='访问时间'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['-updated_at'], name='wallpaper_w_updated_8a6fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['-score'], name='wallpaper_w_score_37b524_idx'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['is_active', '-updated_at'], name='wallpaper_w_is_acti_91a70c_idx'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['classify', '-updated_at'], name='wallpaper_w_classif_f800de_idx'),
        ),
    ]
