# Generated by Django 5.2 on 2026-04-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0048_versions_remove_wall_wallpaper_w_classif_b6c121_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='图片高度'),
        ),
        migrations.AddField(
            model_name='wall',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='图片宽度'),
        ),
    ]
