# Generated by Django 5.2 on 2026-05-13 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0049_wall_height_wall_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(choices=[('view', '浏览'), ('like', '点赞'), ('favorite', '收藏'), ('download', '下载'), ('share', '分享'), ('comment', '评论'), ('rate', '评分')], max_length=20, verbose_name='操作类型')),
                ('action_value', models.CharField(blank=True, max_length=20, null=True, verbose_name='操作值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'db_table': 'wallpaper_user_actions',
                'db_table_comment': '用户操作日志表',
            },
        ),
        migrations.RemoveField(
            model_name='actions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='actions',
            name='wall',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='tabs',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='wall',
            old_name='tabs',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='access',
            name='device_brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备品牌'),
        ),
        migrations.AddField(
            model_name='access',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='access',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备型号'),
        ),
        migrations.AddField(
            model_name='wall',
            name='comments',
            field=models.IntegerField(blank=True, db_default=0, default=0, null=True, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='wall',
            name='favorites',
            field=models.IntegerField(blank=True, db_default=0, default=0, null=True, verbose_name='收藏数'),
        ),
        migrations.AddField(
            model_name='wall',
            name='likes',
            field=models.IntegerField(blank=True, db_default=0, default=0, null=True, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='wall',
            name='shares',
            field=models.IntegerField(blank=True, db_default=0, default=0, null=True, verbose_name='分享数'),
        ),
        migrations.AddField(
            model_name='wall',
            name='trends',
            field=models.FloatField(blank=True, db_default=0, default=0, null=True, verbose_name='趋势评分'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='downloads',
            field=models.IntegerField(blank=True, db_default=0, default=0, null=True, verbose_name='下载量'),
        ),
        migrations.AlterField(
            model_name='wall',
            name='views',
            field=models.IntegerField(blank=True, db_default=0, default=0, null=True, verbose_name='浏览量'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['-trends'], name='wallpaper_w_trends_858a7f_idx'),
        ),
        migrations.AddField(
            model_name='useractions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AddField(
            model_name='useractions',
            name='wall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.wall', verbose_name='壁纸id'),
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.AddIndex(
            model_name='useractions',
            index=models.Index(fields=['-created_at'], name='wallpaper_u_created_98a647_idx'),
        ),
        migrations.AddIndex(
            model_name='useractions',
            index=models.Index(fields=['user', '-created_at'], name='wallpaper_u_user_id_8281de_idx'),
        ),
    ]
