# Generated by Django 5.2 on 2026-05-13 01:59

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0050_useractions_remove_actions_user_remove_actions_wall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractions',
            name='created_at',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now(), verbose_name='创建时间'),
        ),
    ]
