# Generated by Django 5.2 on 2026-05-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0051_alter_useractions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
