# Generated by Django 5.2 on 2026-05-13 06:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0052_alter_useractions_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='useractions',
            name='wallpaper_u_created_98a647_idx',
        ),
        migrations.RemoveIndex(
            model_name='useractions',
            name='wallpaper_u_user_id_8281de_idx',
        ),
        migrations.AddField(
            model_name='useractions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='action_value',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='操作值'),
        ),
        migrations.AlterUniqueTogether(
            name='useractions',
            unique_together={('user', 'wall', 'action_key')},
        ),
        migrations.AddIndex(
            model_name='useractions',
            index=models.Index(fields=['user', 'action_key', '-updated_at'], name='wallpaper_u_user_id_40e626_idx'),
        ),
    ]
