# Generated by Django 5.2 on 2026-05-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0053_remove_useractions_wallpaper_u_created_98a647_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractions',
            name='action_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='操作值'),
        ),
    ]
