# Generated by Django 5.2 on 2026-05-18 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0054_alter_useractions_action_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='access',
            name='language',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='语言'),
        ),
        migrations.AddField(
            model_name='useractions',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备id'),
        ),
        migrations.AddField(
            model_name='wall',
            name='normalized_trends',
            field=models.FloatField(blank=True, db_default=0, default=0, null=True, verbose_name='归一化趋势评分'),
        ),
        migrations.AlterField(
            model_name='wallfeatures',
            name='feature_dim',
            field=models.IntegerField(blank=True, null=True, verbose_name='壁纸特征维度'),
        ),
        migrations.AlterField(
            model_name='wallfeatures',
            name='feature_vector',
            field=models.BinaryField(blank=True, null=True, verbose_name='壁纸特征向量'),
        ),
        migrations.AddIndex(
            model_name='useractions',
            index=models.Index(fields=['device_id', 'action_key', '-updated_at'], name='wallpaper_u_device__5e63e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractions',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'wall', 'action_key'), name='unique_user_action'),
        ),
        migrations.AddConstraint(
            model_name='useractions',
            constraint=models.UniqueConstraint(condition=models.Q(('device_id__isnull', False)), fields=('device_id', 'wall', 'action_key'), name='unique_device_action'),
        ),
    ]
