# Generated by Django 5.2 on 2026-05-18 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0055_alter_useractions_unique_together_access_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='设备id')),
                ('wall_id', models.IntegerField(verbose_name='壁纸id')),
                ('score', models.FloatField(verbose_name='推荐分数')),
                ('reason', models.CharField(blank=True, max_length=60, null=True, verbose_name='推荐原因')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户推荐',
                'verbose_name_plural': '用户推荐',
                'db_table': 'wallpaper_recommendations',
                'db_table_comment': '存储预计算的推荐结果',
                'indexes': [models.Index(fields=['user', '-score'], name='wallpaper_r_user_id_a73448_idx'), models.Index(fields=['device_id', '-score'], name='wallpaper_r_device__e97a1f_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'wall_id'), name='unique_user_recommendation'), models.UniqueConstraint(condition=models.Q(('device_id__isnull', False)), fields=('device_id', 'wall_id'), name='unique_device_recommendation')],
            },
        ),
    ]
