# Generated by Django 5.2 on 2026-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0056_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wall',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='图片分数'),
        ),
    ]
