# Generated by Django 5.2 on 2026-06-12 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0057_alter_wall_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='useractions',
            name='unique_user_action',
        ),
        migrations.RemoveConstraint(
            model_name='useractions',
            name='unique_device_action',
        ),
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_updated_8a6fc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_score_37b524_idx',
        ),
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_classif_f800de_idx',
        ),
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_trends_858a7f_idx',
        ),
        migrations.AlterField(
            model_name='banner',
            name='sort',
            field=models.FloatField(blank=True, null=True, verbose_name='排序字段'),
        ),
        migrations.AlterField(
            model_name='classify',
            name='sort',
            field=models.FloatField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sort',
            field=models.FloatField(blank=True, null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='useractions',
            name='wall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.wall', verbose_name='壁纸id'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['is_active', 'classify', '-updated_at'], name='wallpaper_w_is_acti_74ae66_idx'),
        ),
        migrations.AddConstraint(
            model_name='useractions',
            constraint=models.UniqueConstraint(condition=models.Q(('action_key__isnull', False), ('device_id__isnull', False), ('wall__isnull', False)), fields=('device_id', 'user', 'wall', 'action_key'), name='unique_device_user_action'),
        ),
    ]
