# Generated by Django 5.2 on 2026-06-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0058_remove_useractions_unique_user_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='tags_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='英文标签'),
        ),
    ]
