# Generated by Django 5.2 on 2026-06-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0059_wall_tags_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='公告详情-英文'),
        ),
        migrations.AddField(
            model_name='notice',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='公告标题-英文'),
        ),
    ]
