# Generated by Django 5.2 on 2026-06-30 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0060_notice_content_en_notice_title_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=60, verbose_name='操作类型')),
                ('energy_change', models.IntegerField(verbose_name='能量变化')),
                ('wall_id', models.IntegerField(blank=True, null=True, verbose_name='壁纸id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '能量流水记录',
                'verbose_name_plural': '能量流水记录',
                'db_table': 'wallpaper_energy_log',
                'indexes': [models.Index(fields=['user', 'action_type', '-created_at'], name='wallpaper_e_user_id_1fa6c3_idx')],
            },
        ),
    ]
