# Generated by Django 5.2 on 2026-07-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0061_energylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energylog',
            options={'verbose_name': '能量流水记录', 'verbose_name_plural': '能量流水记录_plural'},
        ),
        migrations.AlterModelOptions(
            name='useractions',
            options={'verbose_name': '用户操作日志', 'verbose_name_plural': '用户操作日志_plural'},
        ),
        migrations.AddField(
            model_name='useractions',
            name='channel',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='渠道'),
        ),
    ]
