# Generated by Django 5.2 on 2026-07-16 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0063_profile_birthday_profile_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套餐名称')),
                ('name_en', models.CharField(max_length=100, verbose_name='套餐名称(英文)')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='套餐编码标识')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现价')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('period_days', models.IntegerField(verbose_name='有效天数')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='营销文案')),
                ('description_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='营销文案(英文)')),
                ('recommended', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='上下架状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'VIP商品套餐',
                'verbose_name_plural': 'VIP商品套餐',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=64, unique=True, verbose_name='系统单号')),
                ('product_name', models.CharField(max_length=100, verbose_name='商品名称(快照)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现价(快照)')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原价(快照)')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种(快照)')),
                ('period_days', models.IntegerField(verbose_name='有效天数(快照)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际支付金额')),
                ('platform', models.CharField(max_length=50, verbose_name='支付来源')),
                ('payment_method', models.CharField(default='alipay', max_length=50, verbose_name='支付方式')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('transaction_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='三方流水单号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付成功时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.product', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
            },
        ),
    ]
