# Generated by Django 5.2 on 2026-07-17 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0064_product_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品信息', 'verbose_name_plural': '商品信息'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='order',
            name='device_id',
            field=models.CharField(default='', max_length=128, verbose_name='设备ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_expire_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='VIP过期时间'),
        ),
        migrations.AlterField(
            model_name='energylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wallpaper.product', verbose_name='关联商品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, null=True, verbose_name='性别'),
        ),
    ]
