# Generated by Django 5.2 on 2026-07-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0065_alter_product_options_remove_profile_is_vip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': '访问日志详情', 'verbose_name_plural': 'Accesses 访问日志'},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'app应用', 'verbose_name_plural': 'Applications 应用管理'},
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页横幅', 'verbose_name_plural': 'Banners 首页横幅'},
        ),
        migrations.AlterModelOptions(
            name='classify',
            options={'verbose_name': '分类', 'verbose_name_plural': 'Classify 壁纸分类'},
        ),
        migrations.AlterModelOptions(
            name='energylog',
            options={'verbose_name': '能量流水记录', 'verbose_name_plural': 'EnergyLogs 能量流水记录'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': '反馈信息', 'verbose_name_plural': 'Feedbacks 反馈信息'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '公告', 'verbose_name_plural': 'Notices 公告信息'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '交易订单', 'verbose_name_plural': 'Orders 交易订单'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品信息', 'verbose_name_plural': 'Products 商品信息'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '个人信息', 'verbose_name_plural': 'Profiles 用户个人信息'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '专题', 'verbose_name_plural': 'Subjects 专题'},
        ),
        migrations.AlterModelOptions(
            name='useractions',
            options={'verbose_name': '用户操作日志', 'verbose_name_plural': 'UserActions 用户操作日志'},
        ),
        migrations.AlterModelOptions(
            name='versions',
            options={'verbose_name': '版本信息', 'verbose_name_plural': 'Versions 版本信息'},
        ),
        migrations.AlterModelOptions(
            name='wall',
            options={'verbose_name': '壁纸', 'verbose_name_plural': 'Wallpapers 壁纸信息'},
        ),
        migrations.AlterModelOptions(
            name='wallfeatures',
            options={'verbose_name': '壁纸特征向量', 'verbose_name_plural': 'WallpaperFeatures 壁纸特征向量'},
        ),
        migrations.AlterModelOptions(
            name='wallsimilarities',
            options={'verbose_name': '壁纸相似度', 'verbose_name_plural': 'WallpaperSimilarities 壁纸相似度'},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='picurl',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sort',
        ),
        migrations.AddField(
            model_name='classify',
            name='classify_type',
            field=models.IntegerField(blank=True, choices=[(1, '手机壁纸'), (2, '横屏壁纸'), (3, '动态壁纸'), (4, '头像')], default=1, null=True, verbose_name='分类类型'),
        ),
    ]
