# Generated by Django 5.2 on 2026-07-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0066_alter_access_options_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)'),
        ),
    ]
