# Generated by Django 6.0.7 on 2026-07-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0067_wall_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wall',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='versions',
            name='ad_enabled',
            field=models.BooleanField(default=True, help_text='关闭后客户端隐藏广告并降级引导VIP', verbose_name='是否开启广告/审核开关'),
        ),
        migrations.AddField(
            model_name='versions',
            name='is_force_update',
            field=models.BooleanField(default=False, verbose_name='是否强制更新'),
        ),
        migrations.AddField(
            model_name='versions',
            name='update_log',
            field=models.TextField(blank=True, null=True, verbose_name='更新日志'),
        ),
        migrations.AddField(
            model_name='versions',
            name='update_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='更新标题'),
        ),
        migrations.AddField(
            model_name='versions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='wall',
            name='access_level',
            field=models.IntegerField(choices=[(0, '免费'), (1, '看广告/VIP'), (2, 'VIP专属')], default=0, help_text='0:免费 1:看广告或VIP 2:仅VIP专属', verbose_name='解锁级别'),
        ),
        migrations.AlterField(
            model_name='versions',
            name='app_store_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='应用商店/下载地址'),
        ),
        migrations.AlterField(
            model_name='versions',
            name='channel',
            field=models.CharField(blank=True, default='official', max_length=100, null=True, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='versions',
            name='platform',
            field=models.CharField(help_text='如: mp-weixin, app-vivo, app-harmony, app-android, app-ios', max_length=100, verbose_name='平台'),
        ),
    ]
