# Generated by Django 6.0.7 on 2026-07-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0068_remove_wall_is_locked_versions_ad_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_is_acti_91a70c_idx',
        ),
        migrations.RemoveIndex(
            model_name='wall',
            name='wallpaper_w_is_acti_74ae66_idx',
        ),
        migrations.AlterField(
            model_name='versions',
            name='platform',
            field=models.CharField(help_text='如: mp-weixin, harmony, android, ios', max_length=100, verbose_name='平台'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['is_active', '-created_at'], name='wallpaper_w_is_acti_b0c17d_idx'),
        ),
        migrations.AddIndex(
            model_name='wall',
            index=models.Index(fields=['is_active', 'classify', '-created_at'], name='wallpaper_w_is_acti_a6da45_idx'),
        ),
    ]
