# Generated by Django 6.0.7 on 2026-07-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0069_remove_wall_wallpaper_w_is_acti_91a70c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='versions',
            name='pay_enabled',
            field=models.BooleanField(default=True, help_text='关闭后客户端隐藏VIP充值/支付入口', verbose_name='是否开启支付功能'),
        ),
    ]
