# Generated by Django 6.0.7 on 2026-08-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0070_versions_pay_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='app_theme',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='应用主题'),
        ),
        migrations.AddField(
            model_name='access',
            name='os_theme',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='系统主题'),
        ),
        migrations.AlterField(
            model_name='versions',
            name='ad_enabled',
            field=models.BooleanField(default=True, help_text='关闭后客户端隐藏广告并降级引导VIP', verbose_name='是否开启广告功能'),
        ),
        migrations.AlterField(
            model_name='versions',
            name='channel',
            field=models.CharField(blank=True, help_text='如：google、xiaomi、huawei、vivo、oppo等', max_length=100, null=True, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='versions',
            name='platform',
            field=models.CharField(help_text='如: mp-weixin, harmony, android, ios等', max_length=100, verbose_name='平台'),
        ),
    ]
