# Generated by Django 6.0.7 on 2026-08-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0071_access_app_theme_access_os_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付渠道'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='支付平台'),
        ),
    ]
