# Generated by Django 6.0.7 on 2026-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0072_order_channel_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(choices=[(0, '国内'), (1, '国外')], default=0, verbose_name='商品类别'),
        ),
        migrations.AddField(
            model_name='versions',
            name='set_wallpaper_enabled',
            field=models.BooleanField(default=False, help_text='关闭后客户端隐藏直接设置壁纸入口', verbose_name='是否开启直接设置壁纸功能'),
        ),
    ]
