# Generated by Django 6.0.7 on 2026-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0073_product_category_versions_set_wallpaper_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='huawei_openid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='华为openid'),
        ),
        migrations.AddField(
            model_name='profile',
            name='huawei_unionid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='华为unionid'),
        ),
    ]
