# Generated by Django 6.0.7 on 2026-08-18 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0074_profile_huawei_openid_profile_huawei_unionid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='搜索关键词')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='累计搜索次数')),
                ('result_count_last', models.IntegerField(default=0, verbose_name='最近一次命中数量')),
                ('has_results', models.BooleanField(default=True, help_text='为否表示用户搜索但壁纸库未收录，需重点补库', verbose_name='是否有壁纸收录')),
                ('is_recommend', models.BooleanField(default=False, help_text='勾选后可在前端搜索页推荐热搜列表中展示', verbose_name='推荐热搜词')),
                ('sort', models.FloatField(default=0, help_text='数字越大越靠前', verbose_name='推荐排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='首次搜索时间')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='最近搜索时间')),
            ],
            options={
                'verbose_name': '搜索关键词',
                'verbose_name_plural': 'SearchKeywords 搜索关键词统计',
                'ordering': ['-search_count'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=100, verbose_name='搜索关键词')),
                ('result_count', models.IntegerField(default=0, verbose_name='命中结果数')),
                ('device_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备ID')),
                ('platform', models.CharField(blank=True, max_length=50, null=True, verbose_name='平台/渠道')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='搜索时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='搜索用户')),
            ],
            options={
                'verbose_name': '搜索明细日志',
                'verbose_name_plural': 'SearchLogs 搜索明细日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
