# Generated by Django 6.0.7 on 2026-08-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0075_searchkeyword_searchlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlog',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='渠道'),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='平台'),
        ),
    ]
