# Generated by Django 6.0.7 on 2026-08-26 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0076_searchlog_channel_alter_searchlog_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='画板名称')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='画板简介')),
                ('is_auto_rotate', models.BooleanField(default=False, verbose_name='开启自动轮播')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '壁纸画板',
                'verbose_name_plural': 'Boards 壁纸画板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAutoRotateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='开启自动切换')),
                ('mode', models.CharField(choices=[('bing', '每日必应'), ('board', '画板轮播')], default='bing', max_length=20, verbose_name='切换模式')),
                ('target', models.CharField(choices=[('both', '双屏同时'), ('lock', '锁屏壁纸'), ('home', '桌面壁纸')], default='both', max_length=20, verbose_name='应用目标')),
                ('frequency', models.CharField(choices=[('daily', '每天一次'), ('12h', '每12小时'), ('6h', '每6小时'), ('1h', '每1小时'), ('unlock', '每次亮屏解锁')], default='daily', max_length=20, verbose_name='切换频率')),
                ('strategy', models.CharField(choices=[('random', '随机轮播'), ('sequential', '顺序循环')], default='random', max_length=20, verbose_name='轮播策略')),
                ('wifi_only', models.BooleanField(default=True, verbose_name='仅在WiFi下下载')),
                ('rotate_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='快捷指令Token')),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True, verbose_name='最近切换时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.board', verbose_name='指定轮播画板')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_rotate_config', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '自动换壁纸配置',
                'verbose_name_plural': 'UserAutoRotateConfigs 自动换壁纸配置',
            },
        ),
        migrations.CreateModel(
            name='BoardWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wallpaper.board', verbose_name='所属画板')),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_items', to='wallpaper.wall', verbose_name='关联壁纸')),
            ],
            options={
                'verbose_name': '画板壁纸关联',
                'verbose_name_plural': 'BoardWalls 画板壁纸关联',
                'ordering': ['sort_order', '-added_at'],
                'unique_together': {('board', 'wall')},
            },
        ),
    ]
