# Generated by Django 6.0.7 on 2026-08-27 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0077_board_userautorotateconfig_boardwall'),
    ]

    operations = [
        migrations.AddField(
            model_name='userautorotateconfig',
            name='last_wall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallpaper.wall', verbose_name='上次轮播壁纸'),
        ),
    ]
