# Generated by Django 6.0.7 on 2026-09-07 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0078_userautorotateconfig_last_wall'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='体验码')),
                ('title', models.CharField(default='小红书推广体验', max_length=100, verbose_name='活动名称')),
                ('reward_days', models.PositiveIntegerField(default=3, verbose_name='赠送VIP天数')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='最大可用次数')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('valid_end', models.DateTimeField(blank=True, null=True, verbose_name='有效期截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '体验码',
                'verbose_name_plural': 'RedeemCodes 体验码管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedeemRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_desc', models.CharField(max_length=100, verbose_name='获得权益描述')),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True, verbose_name='兑换IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='wallpaper.redeemcode', verbose_name='对应体验码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_records', to=settings.AUTH_USER_MODEL, verbose_name='兑换用户')),
            ],
            options={
                'verbose_name': '兑换明细记录',
                'verbose_name_plural': 'RedeemRecords 兑换明细记录',
                'ordering': ['-created_at'],
                'unique_together': {('code', 'user')},
            },
        ),
    ]
