# Generated by Django 6.0.7 on 2026-09-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0079_redeemcode_redeemrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wx_product_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='微信虚拟支付道具ID'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wechat_session_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='微信session_key'),
        ),
    ]
