# Generated by Django 6.0.7 on 2026-09-08 04:23

import wallpaper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0080_product_wx_product_id_profile_wechat_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemcode',
            name='code',
            field=models.CharField(db_index=True, default=wallpaper.models.generate_redeem_code, max_length=32, unique=True, verbose_name='体验码'),
        ),
    ]
