# Generated by Django 6.0.7 on 2026-09-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaper', '0081_alter_redeemcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wx_product_id',
            field=models.CharField(blank=True, help_text='微信公众平台->虚拟支付->道具管理中创建并已发布的道具ID（未填写时默认使用套餐编码）', max_length=64, null=True, verbose_name='微信虚拟支付道具ID'),
        ),
    ]
